name: flutter_embed_unity_android_example
publish_to: none
description: Demonstrates how to use the flutter_embed_unity_android plugin.
version: 1.0.0+2
environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  change_app_package_name: ^1.2.0
  dio: ^5.4.3+1
  dropdown_search: ^5.0.6
  flutter:
    sdk: flutter
  flutter_embed_unity: ^1.1.0
  flutter_embed_unity_2022_3_android: ^1.1.0
  flutter_markdown: ^0.7.1
  # flutter_ra_availambility: ^1.0.0
  flutter_svg: ^2.0.10+1
  flutter_switch: ^0.3.2
  flutter_widget_from_html: ^0.15.0
  get: 4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  intl: any
  just_audio: ^0.9.38
  lottie: ^3.1.0
  percent_indicator: ^4.2.3
  permission_handler: ^11.3.1
  shimmer: ^3.0.0
  torch_controller: ^2.0.1
  youtube_player_flutter: ^9.0.1

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
    - assets/svg/

  fonts:
    - family: Gilroy
      fonts:
        - asset: fonts/Gilroy-Regular.ttf

    - family: Gilroy-Bold
      fonts:
        - asset: fonts/Gilroy-Bold.ttf
          weight: 700
    - family: Gilroy-Medium
      fonts:
        - asset: fonts/Gilroy-Medium.ttf
          weight: 500
    - family: Gilroy-SemiBold
      fonts:
        - asset: fonts/Gilroy-SemiBold.ttf
          weight: 600
    - family: Gilroy-Black
      fonts:
        - asset: fonts/Gilroy-Black.ttf
          weight: 800

    - family: PoetsenOne
      fonts:
        - asset: fonts/PoetsenOne-Regular.ttf
flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/logo_app.png"
  min_sdk_android: 21
